const ROLES = ["STUDENT", "ADMIN", "TEACHER"];
const LESSON_TYPES = ["VIDEO", "TEXT", "TEST"];
const SUBMISSION_STATUSES = ["NOT_REVIEWED", "REVIEWED"];
const VERIFICATION_PURPOSES = ["REGISTER", "RESET"];

const MAX_UPLOAD_BYTES = 10 * 1024 * 1024; // 10MB — ТЗ §9 javobi

module.exports = { ROLES, LESSON_TYPES, SUBMISSION_STATUSES, VERIFICATION_PURPOSES, MAX_UPLOAD_BYTES };
