// Hemis.uz (https://student.hemis.uz/rest/v1/public/university-api-urls) dan olingan
// O'zbekistondagi oliy ta'lim muassasalari ro'yxati — ro'yxatdan o'tish/profil
// formalarida avtomatik to'ldirish (autocomplete) uchun. "abbr" — nomdan avtomatik
// yasalgan qisqartma (masalan "Islom Karimov nomidagi Toshkent davlat texnika
// universiteti" -> "TDTU"), qidiruvda to'liq nom bilan bir qatorda ishlatiladi.
export const UNIVERSITIES = [
  { "name": "“Cyber university” davlat universiteti", "abbr": "CUDU" },
  { "name": "“INTERNATIONAL SCHOOL OF FINANCE TECHNOLOGY AND SCIENCE” institut", "abbr": "ISOFTASI" },
  { "name": "\"Ipak yo‘li\" turizm va madaniy meros xalqaro universiteti", "abbr": "IYTMMXU" },
  { "name": "\"Riga Nordic University\"ning Farg'ona shahridagi filiali", "abbr": "RNUFSF" },
  { "name": "\"TIQXMMI\" Milliy tadqiqot universitetining Qarshi irrigatsiya va agrotexnologiyalar instituti", "abbr": "TMTUQIAI" },
  { "name": "\"TIQXMMI\" MTU Buxoro tabiiy resurslarni boshqarish intitituti", "abbr": "TMBTRBI" },
  { "name": "\"Toshkent irrigatsiya va qishloq xo‘jaligini mexanizatsiyalash muhandislari instituti\" Milliy tadqiqot universiteti", "abbr": "TIQXMMIMTU" },
  { "name": "«Sankt-Peterburg davlat universiteti» Federal davlat byudjeti oliy taʻlim muassasasi Toshkent shahridagi filiali", "abbr": "DUFDBOTMTSF" },
  { "name": "A.Avloniy nomidagi pedagogik mahorat milliy instituti", "abbr": "PMMI" },
  { "name": "Abu Ali ibn Sino nomidagi Buxoro davlat tibbiyot instituti", "abbr": "BDTI" },
  { "name": "Abu Rayhon Beruniy nomidagi Urganch davlat universiteti", "abbr": "UDU" },
  { "name": "Abu Rayhon Beruniy universiteti", "abbr": "ARBU" },
  { "name": "Abu Rayhon Beruniy universiteti NTM (Qarshi kampusi)", "abbr": "ARBUNQK" },
  { "name": "Abu Rayhon Beruniy universiteti NTM (Samarqand kampusi)", "abbr": "ARBUNSK" },
  { "name": "AFRASIAB UNIVERSITY", "abbr": "AU" },
  { "name": "Ajiniyoz nomidagi Nukus davlat pedagogika instituti", "abbr": "NDPI" },
  { "name": "Al-Xorazmiy Universiteti", "abbr": "AU" },
  { "name": "ALFRAGANUS UNIVERSITY", "abbr": "AU" },
  { "name": "Alisher Navoiy nomidagi Toshkent davlat o‘zbek tili va adabiyoti universiteti", "abbr": "TDOTAU" },
  { "name": "Amerika texnologiyalar universiteti", "abbr": "ATU" },
  { "name": "Andijon davlat pedagogika instituti", "abbr": "ADPI" },
  { "name": "Andijon davlat texnika instituti", "abbr": "ADTI" },
  { "name": "Andijon davlat tibbiyot instituti", "abbr": "ADTI" },
  { "name": "Andijon davlat universiteti", "abbr": "ADU" },
  { "name": "Andijon davlat chet tillari instituti", "abbr": "ADCTI" },
  { "name": "Andijon iqtisodiyot va qurilish instituti", "abbr": "AIQI" },
  { "name": "Andijon mashinasozlik instituti", "abbr": "AMI" },
  { "name": "Andijon qishloq xo‘jaligi va agrotexnologiyalar instituti", "abbr": "AQXAI" },
  { "name": "Angren universiteti", "abbr": "AU" },
  { "name": "Aniq va ijtimoiy fanlar universiteti", "abbr": "AIFU" },
  { "name": "Astraxan davlat texnika universitetining Toshkent viloyatidagi filiali", "abbr": "ADTUTVF" },
  { "name": "Axborot texnologiyalari va menejment universiteti", "abbr": "ATMU" },
  { "name": "Acharya universiteti", "abbr": "AU" },
  { "name": "Berdaq nomidagi Qoraqalpoq davlat universiteti", "abbr": "QDU" },
  { "name": "Biznes va tadbirkorlik oliy maktabi", "abbr": "BTOM" },
  { "name": "Botir Zokirov nomidagi Milliy estrada san'ati instituti", "abbr": "MESI" },
  { "name": "British Management University in Tashkent", "abbr": "BMUIT" },
  { "name": "Buxoro davlat pedagogika instituti", "abbr": "BDPI" },
  { "name": "Buxoro davlat texnika universiteti", "abbr": "BDTU" },
  { "name": "Buxoro davlat universiteti", "abbr": "BDU" },
  { "name": "Buxoro innovatsion ta'lim va tibbiyot universiteti", "abbr": "BITTU" },
  { "name": "Buxoro innovatsiyalar universiteti", "abbr": "BIU" },
  { "name": "Buxoro muhandislik-texnologiya instituti", "abbr": "BMI" },
  { "name": "Buxoro xalqaro universiteti", "abbr": "BXU" },
  { "name": "Central Asian Medical University tibbiyot universiteti", "abbr": "CAMUTU" },
  { "name": "Central Asian University", "abbr": "CAU" },
  { "name": "D.I.Mendeleev nomidagi Rossiya kimyo-texnologiya universiteti Federal davlat byudjeti oliy taʻlim muassasasining Toshkent filiali", "abbr": "RKUFDBOTMTF" },
  { "name": "Digital university", "abbr": "DU" },
  { "name": "Diplomat University", "abbr": "DU" },
  { "name": "EMU UNIVERSITY (EURASIAN MULTIDISCIPLINARY UNIVERSITY)", "abbr": "EUEMU" },
  { "name": "Farmatsevtika ta'lim va tadqiqot instituti", "abbr": "FTTI" },
  { "name": "Farmatsevtika texnik universiteti", "abbr": "FTU" },
  { "name": "Farg'ona davlat texnika universiteti", "abbr": "FDTU" },
  { "name": "Farg‘ona davlat universiteti", "abbr": "FDU" },
  { "name": "Farg‘ona jamoat salomatligi tibbiyot instituti", "abbr": "FJSTI" },
  { "name": "Farg‘ona politexnika instituti", "abbr": "FPI" },
  { "name": "Farg'ona shahridagi Koreya xalqaro universiteti", "abbr": "FSKXU" },
  { "name": "Federal davlat avtonom oliy taʻlim muassasasi Milliy texnologik tadqiqotlar universiteti MISiS ning Olmaliq shahridagi filiali", "abbr": "FDAOTMMTTUMNOSF" },
  { "name": "G.V.Plexanov nomli Rossiya iqtisodiyot universiteti Toshkent filiali", "abbr": "GNRIUTF" },
  { "name": "Geologiya fanlari universiteti", "abbr": "GFU" },
  { "name": "Guliston davlat pedagogika instituti", "abbr": "GDPI" },
  { "name": "Guliston davlat universiteti", "abbr": "GDU" },
  { "name": "Hadis ilmi maktabi", "abbr": "HIM" },
  { "name": "HEMIS axborot tizimi universiteti", "abbr": "HATU" },
  { "name": "I.M.Gubkin nomidagi Rossiya davlat neft va gaz universiteti Toshkent shahridagi filiali", "abbr": "RDNGUTSF" },
  { "name": "Imom Buxoriy nomidagi Toshkent islom instituti", "abbr": "TII" },
  { "name": "Imom Termiziy nomidagi islom instituti", "abbr": "II" },
  { "name": "IMPULS  tibbiyot instituti", "abbr": "ITI" },
  { "name": "IMPULS  tibbiyot instituti (Chirchiq kampusi)", "abbr": "ITICK" },
  { "name": "Ipak yo‘li innovatsiyalar universiteti", "abbr": "IYIU" },
  { "name": "Iqtisodiyot va pedagogika universiteti", "abbr": "IPU" },
  { "name": "Iqtisodiyot va pedagogika universiteti (Samarqand kampusi)", "abbr": "IPUSK" },
  { "name": "Is’hoqxon Ibrat nomidagi Namangan davlat chet tillari instituti", "abbr": "NDCTI" },
  { "name": "Islom Karimov nomidagi Toshkent davlat texnika universiteti", "abbr": "TDTU" },
  { "name": "IT Park University", "abbr": "IPU" },
  { "name": "Jahon iqtisodiyoti va diplomatiya universiteti", "abbr": "JIDU" },
  { "name": "Jahon iqtisodiyoti va diplomatiya universiteti huzuridagi Diplomatik akademiya", "abbr": "JIDUHDA" },
  { "name": "Jamoat xavfsizligi universiteti", "abbr": "JXU" },
  { "name": "Japan Digital University", "abbr": "JDU" },
  { "name": "Jismoniy tarbiya va sport ilmiy tadqiqotlar institut", "abbr": "JTSITI" },
  { "name": "Jizzax davlat pedagogika universiteti", "abbr": "JDPU" },
  { "name": "Jizzax politexnika instituti", "abbr": "JPI" },
  { "name": "Jizzax shahridagi “Qozon (Volgabo‘yi) federal universiteti” federal davlat avtonom oliy ta’lim muassasasining filiali", "abbr": "JSQVFUFDAOTMF" },
  { "name": "Kamoliddin Behzod nomidagi Milliy rassomlik va dizayn instituti", "abbr": "MRDI" },
  { "name": "Kattaqo‘rg‘on davlat pedagogika instituti", "abbr": "KDPI" },
  { "name": "M.V.Lomonosov nomidagi Moskva davlat universitetining Toshkent shahridagi filiali", "abbr": "MDUTSF" },
  { "name": "Markaziy Osiyo atrof-muhit va iqlim o‘zgarishini o‘rganish universiteti (Green University)", "abbr": "MOAIOOUGU" },
  { "name": "Maʻmun universiteti", "abbr": "MU" },
  { "name": "Mehnat va ijtimoiy munosabatlar akademiyasi", "abbr": "MIMA" },
  { "name": "MEI milliy tadqiqot universiteti Federal davlat byudjeti oliy taʻlim muassasasining Toshkent filiali", "abbr": "MMTUFDBOTMTF" },
  { "name": "Millat umidi universiteti", "abbr": "MUU" },
  { "name": "Mir arab oliy madrasasi", "abbr": "MAOM" },
  { "name": "Mirzo Ulug‘bek nomidagi O‘zbekiston Milliy universiteti", "abbr": "OMU" },
  { "name": "Mirzo Ulug‘bek nomidagi O‘zbekiston Milliy universiteti Jizzax filiali", "abbr": "OMUJF" },
  { "name": "MMFI milliy tadqiqot yadro universiteti federal davlat avtonom oliy taʻlim muassasasining Toshkent shahridagi filiali", "abbr": "MMTYUFDAOTMTSF" },
  { "name": "Muhammad al-Xorazmiy nomidagi Toshkent axborot texnologiyalari universiteti", "abbr": "TATU" },
  { "name": "Namangan davlat pedagogika instituti", "abbr": "NDPI" },
  { "name": "Namangan davlat texnika universiteti", "abbr": "NDTU" },
  { "name": "Namangan davlat universiteti", "abbr": "NDU" },
  { "name": "Namangan muhandislik-qurilish instituti", "abbr": "NMI" },
  { "name": "Namangan muhandislik-texnologiya instituti", "abbr": "NMI" },
  { "name": "Namangan to'qimachilik sanoati instituti", "abbr": "NTSI" },
  { "name": "Namangan Xalqaro Universiteti", "abbr": "NXU" },
  { "name": "Navoiy davlat konchilik  va texnologiyalar universiteti  huzuridagi Nukus konchilik instituti", "abbr": "NDKTUHNKI" },
  { "name": "Navoiy davlat konchilik va texnologiyalar universiteti", "abbr": "NDKTU" },
  { "name": "Navoiy davlat universiteti", "abbr": "NDU" },
  { "name": "Navoiy innovatsiyalar universiteti", "abbr": "NIU" },
  { "name": "Navoiy innovatsiyalar universiteti (Surxondaryo kampusi)", "abbr": "NIUSK" },
  { "name": "Nizomiy nomidagi Oʻzbekiston milliy pedagogika universiteti", "abbr": "OMPU" },
  { "name": "Nukus davlat texnika universiteti", "abbr": "NDTU" },
  { "name": "Olmaliq davlat texnika instituti", "abbr": "ODTI" },
  { "name": "Oriental universiteti", "abbr": "OU" },
  { "name": "Osiyo texnologiyalar universiteti", "abbr": "OTU" },
  { "name": "Osiyo xalqaro universiteti", "abbr": "OXU" },
  { "name": "Osiyo xalqaro universiteti Xorazm filiali", "abbr": "OXUXF" },
  { "name": "Oxus University", "abbr": "OU" },
  { "name": "Oziq-ovqat texnologiyasi va muhandisligi xalqaro instituti", "abbr": "OTMXI" },
  { "name": "Oʼzbekistondagi Sharda universiteti", "abbr": "OSU" },
  { "name": "PDP University", "abbr": "PU" },
  { "name": "Perfect University", "abbr": "PU" },
  { "name": "Pisa university in Tashkent", "abbr": "PUIT" },
  { "name": "Profi University", "abbr": "PU" },
  { "name": "Profi University Navoiy filliali", "abbr": "PUNF" },
  { "name": "Qarshi davlat texnika universiteti", "abbr": "QDTU" },
  { "name": "Qarshi davlat universiteti", "abbr": "QDU" },
  { "name": "Qarshi muhandislik-iqtisodiyot instituti", "abbr": "QMI" },
  { "name": "Qarshi xalqaro universiteti", "abbr": "QXU" },
  { "name": "Qoraqalpog'iston qishloq xo'jaligi va agrotexnologiyalar instituti", "abbr": "QQXAI" },
  { "name": "Qoraqalpogʻiston tibbiyot instituti", "abbr": "QTI" },
  { "name": "Qo‘qon davlat pedagogika instituti", "abbr": "QDPI" },
  { "name": "Qo'qon davlat universiteti", "abbr": "QDU" },
  { "name": "Qo‘qon universiteti", "abbr": "QU" },
  { "name": "Qo'qon universiteti Andijon filiali", "abbr": "QUAF" },
  { "name": "Raqamli iqtisodiyot va agrotexnologiyalar universiteti", "abbr": "RIAU" },
  { "name": "Renaissance University", "abbr": "RU" },
  { "name": "Renessans ta'lim universiteti", "abbr": "RTU" },
  { "name": "Rossiya Federatsiyasi Tashqi ishlar vazirligining Moskva davlat xalqaro munosabatlar instituti (universiteti)” Federal davlat avtonom oliy ta’lim muassasasining Toshkent shahridagi filiali", "abbr": "RFTIVMDXMIUFDAOTMTSF" },
  { "name": "Samarqand agroinnovatsiyalar va tadqiqotlar instituti", "abbr": "SATI" },
  { "name": "Samarqand davlat pedagogika instituti", "abbr": "SDPI" },
  { "name": "Samarqand davlat texnika universiteti", "abbr": "SDTU" },
  { "name": "Samarqand davlat tibbiyot universiteti", "abbr": "SDTU" },
  { "name": "Samarqand davlat universitetining Denov tadbirkorlik va pedagogika instituti", "abbr": "SDUDTPI" },
  { "name": "Samarqand davlat veterinariya meditsinasi, chorvachilik va biotexnologiyalar universiteti", "abbr": "SDVMCBU" },
  { "name": "Samarqand davlat veterinariya meditsinasi, chorvachilik va biotexnologiyalar universiteti Nukus filiali", "abbr": "SDVMCBUNF" },
  { "name": "Samarqand davlat veterinariya meditsinasi, chorvachilik va biotexnologiyalar universitetining Toshkent filiali", "abbr": "SDVMCBUTF" },
  { "name": "Samarqand davlat chet tillar instituti", "abbr": "SDCTI" },
  { "name": "Samarqand iqtisodiyot va servis instituti", "abbr": "SISI" },
  { "name": "Samarqand Xalqaro Texnologiya Universiteti", "abbr": "SXTU" },
  { "name": "SAMBHRAM universitet", "abbr": "SU" },
  { "name": "Sarbon universiteti", "abbr": "SU" },
  { "name": "Soliq oliy maktabi", "abbr": "SOM" },
  { "name": "STARS International University", "abbr": "SIU" },
  { "name": "Tashkent international university", "abbr": "TIU" },
  { "name": "Tashkent International University Andijon Kampusi", "abbr": "TIUAK" },
  { "name": "Tashkent International University of Education xalqaro universiteti", "abbr": "TIUOEXU" },
  { "name": "Tashkent Metropolitan University", "abbr": "TMU" },
  { "name": "TEAM University", "abbr": "TU" },
  { "name": "Termiz agrotexnologiyalar va innovatsion rivojlanish instituti", "abbr": "TAIRI" },
  { "name": "Termiz davlat muhandislik va agrotexnologiyalar universiteti", "abbr": "TDMAU" },
  { "name": "Termiz davlat pedagogika instituti", "abbr": "TDPI" },
  { "name": "Termiz davlat universiteti", "abbr": "TDU" },
  { "name": "Termiz iqtisodiyot va servis universiteti", "abbr": "TISU" },
  { "name": "Termiz muhandislik-texnologiya instituti", "abbr": "TMI" },
  { "name": "TMC INSTITUTE", "abbr": "TI" },
  { "name": "Toshkent amaliy fanlar universiteti", "abbr": "TAFU" },
  { "name": "Toshkent arxitektura-qurilish universiteti", "abbr": "TAU" },
  { "name": "Toshkent arxitektura-qurilish universiteti huzuridagi Integratsiyalashgan Oliy maktabi", "abbr": "TAUHIOM" },
  { "name": "Toshkent axborot texnologiyalari universiteti Farg‘ona filiali", "abbr": "TATUFF" },
  { "name": "Toshkent axborot texnologiyalari universiteti Nukus filiali", "abbr": "TATUNF" },
  { "name": "Toshkent axborot texnologiyalari universiteti Nurafshon filiali", "abbr": "TATUNF" },
  { "name": "Toshkent axborot texnologiyalari universiteti Qarshi filiali", "abbr": "TATUQF" },
  { "name": "Toshkent axborot texnologiyalari universiteti Samarqand filiali", "abbr": "TATUSF" },
  { "name": "Toshkent axborot texnologiyalari universiteti Urganch filiali", "abbr": "TATUUF" },
  { "name": "Toshkent davlat agrar universiteti", "abbr": "TDAU" },
  { "name": "Toshkent davlat iqtisodiyot universiteti", "abbr": "TDIU" },
  { "name": "Toshkent davlat iqtisodiyot universiteti Samarqand filiali", "abbr": "TDIUSF" },
  { "name": "Toshkent davlat stomatologiya instituti", "abbr": "TDSI" },
  { "name": "Toshkent davlat texnika universiteti Qo‘qon filiali", "abbr": "TDTUQF" },
  { "name": "Toshkent davlat tibbiyot universiteti", "abbr": "TDTU" },
  { "name": "Toshkent davlat tibbiyot universiteti Termiz filiali", "abbr": "TDTUTF" },
  { "name": "Toshkent davlat tibbiyot universiteti Chirchiq filiali", "abbr": "TDTUCF" },
  { "name": "Toshkent davlat transport universiteti", "abbr": "TDTU" },
  { "name": "Toshkent davlat yuridik universiteti", "abbr": "TDYU" },
  { "name": "Toshkent davlat sharqshunoslik universiteti", "abbr": "TDSU" },
  { "name": "Toshkent farmatsevtika instituti", "abbr": "TFI" },
  { "name": "Toshkent gumanitar fanlar universiteti", "abbr": "TGFU" },
  { "name": "Toshkent ijtimoiy innovatsiya universiteti", "abbr": "TIIU" },
  { "name": "Toshkent iqtisodiyot va pedagogika universiteti", "abbr": "TIPU" },
  { "name": "Toshkent iqtisodiyot va texnologiyalari universiteti", "abbr": "TITU" },
  { "name": "Toshkent Kimyo xalqaro universiteti", "abbr": "TKXU" },
  { "name": "Toshkent Kimyo xalqaro universiteti Namangan filiali", "abbr": "TKXUNF" },
  { "name": "Toshkent Kimyo xalqaro universiteti Samarqand filiali", "abbr": "TKXUSF" },
  { "name": "Toshkent kimyo-texnologiya instituti", "abbr": "TKI" },
  { "name": "Toshkent kimyo-texnologiya instituti Yangiyer filiali", "abbr": "TKIYF" },
  { "name": "Toshkent kimyo-texnologiya instituti Shahrisabz filiali", "abbr": "TKISF" },
  { "name": "Toshkent menedjment va iqtisodiyot instituti", "abbr": "TMII" },
  { "name": "Toshkent moliya instituti", "abbr": "TMI" },
  { "name": "Toshkent pediatriya tibbiyot instituti", "abbr": "TPTI" },
  { "name": "Toshkent Texnologiyalar universiteti", "abbr": "TTU" },
  { "name": "Toshkent tibbiyot akademiyasi", "abbr": "TTA" },
  { "name": "Toshkent to‘qimachilik va yengil sanoat instituti", "abbr": "TTYSI" },
  { "name": "Toshkent xalqaro moliyaviy boshqaruv va texnologiyalar universiteti", "abbr": "TXMBTU" },
  { "name": "Toshkent Xalqaro Vestminster Universiteti", "abbr": "TXVU" },
  { "name": "Toshkent shahrida S.A Gerasimov nomidagi Butunrossiya davlat kinematografiya universitetining birinchi xorijiy filiali", "abbr": "BDKUBXF" },
  { "name": "Toshkent shahridagi “A.I.Gersen nomidagi Rossiya Davlat pedagogika universiteti” Federal davlat budjeti oliy ta’lim muassasasi filiali", "abbr": "RDPUFDBOTMF" },
  { "name": "Toshkent shahridagi Adju universiteti", "abbr": "TSAU" },
  { "name": "Toshkent shahridagi Amiti universiteti", "abbr": "TSAU" },
  { "name": "Toshkent shahridagi Belarus-Oʼzbekiston qoʻshma tarmoqlararo amaliy texnik kvalifikatsiyalar instituti", "abbr": "TSBQTATKI" },
  { "name": "Toshkent shahridagi Inha Universiteti", "abbr": "TSIU" },
  { "name": "Toshkent shahridagi Puchon universiteti", "abbr": "TSPU" },
  { "name": "Toshkent shahridagi Singapur Menejmentni rivojlantirish instituti", "abbr": "TSSMRI" },
  { "name": "Toshkent shahridagi Turin politexnika universiteti", "abbr": "TSTPU" },
  { "name": "Toshkent shahridagi Turkiyaning iqtisodiyot va texnologiyalar universiteti filiali", "abbr": "TSTITUF" },
  { "name": "Toshkent shahridagi Vebster universitetining taʻlim dasturlarini amalga oshirish markazi", "abbr": "TSVUTDAOM" },
  { "name": "Toshtech texnika universiteti", "abbr": "TTU" },
  { "name": "Turan International University", "abbr": "TIU" },
  { "name": "Turkiston yangi innovatsiyalar universiteti", "abbr": "TYIU" },
  { "name": "Turkiy davlatlar xalqaro universiteti", "abbr": "TDXU" },
  { "name": "Turon universiteti", "abbr": "TU" },
  { "name": "Turon universiteti (Andijon kampusi)", "abbr": "TUAK" },
  { "name": "University of Business and Science", "abbr": "UOBAS" },
  { "name": "University of economics and pedagogy", "abbr": "UOEAP" },
  { "name": "UNIVERSITY OF INNOVATION TECHNOLOGIES", "abbr": "UOIT" },
  { "name": "University of science and technologies", "abbr": "UOSAT" },
  { "name": "Urganch davlat pedagogika instituti", "abbr": "UDPI" },
  { "name": "Urganch davlat tibbiyot instituti", "abbr": "UDTI" },
  { "name": "Urganch Innovatsion Universiteti", "abbr": "UIU" },
  { "name": "Urganch RANCH texnologiya universiteti", "abbr": "URTU" },
  { "name": "Urganch RANCH texnologiya universiteti Nukus kampusi", "abbr": "URTUNK" },
  { "name": "Urganch shahridagi xalqaro binary universiteti", "abbr": "USXBU" },
  { "name": "VARSOVIA BIZNES VA AMALIY FANLAR UNIVERSITETI ANDIJON FILIALI", "abbr": "VBAFUAF" },
  { "name": "Vatan Universiteti", "abbr": "VU" },
  { "name": "Xalqaro ijtimoiy innovatsiyalar universiteti", "abbr": "XIIU" },
  { "name": "Xalqaro innovatsion universitet", "abbr": "XIU" },
  { "name": "Xalqaro Nordik universiteti", "abbr": "XNU" },
  { "name": "Xalqaro qishloq xo'jaligi universiteti", "abbr": "XQXU" },
  { "name": "Yangi Asr Universiteti", "abbr": "YAU" },
  { "name": "Yangi O'zbekiston universiteti", "abbr": "YOU" },
  { "name": "Yunus Rajabiy nomidagi O‘zbek milliy musiqa sanʻati instituti", "abbr": "OMMSI" },
  { "name": "Zarmed Universiteti (Buxoro kampusi)", "abbr": "ZUBK" },
  { "name": "Zarmed universiteti (Samarqand kampusi)", "abbr": "ZUSK" },
  { "name": "O‘zbek-fransuz universiteti", "abbr": "OU" },
  { "name": "O‘zbekiston   davlat jismoniy tarbiya va sport universiteti Nukus filiali", "abbr": "ODJTSUNF" },
  { "name": "O‘zbekiston davlat jahon tillari universiteti", "abbr": "ODJTU" },
  { "name": "Oʻzbekiston davlat jismoniy tarbiya va sport universiteti", "abbr": "ODJTSU" },
  { "name": "Oʻzbekiston davlat jismoniy tarbiya va sport universiteti Fargʻona filiali", "abbr": "ODJTSUFF" },
  { "name": "O‘zbekiston davlat konservatoriyasi", "abbr": "ODK" },
  { "name": "Oʻzbekiston davlat konservatoriyasi Nukus filiali", "abbr": "ODKNF" },
  { "name": "O‘zbekiston davlat san’at va madaniyat instituti", "abbr": "ODSMI" },
  { "name": "O‘zbekiston davlat san’at va madaniyat instituti Nukus filiali", "abbr": "ODSMINF" },
  { "name": "O‘zbekiston davlat san’at va madaniyat institutining Farg‘ona mintaqaviy filiali", "abbr": "ODSMIFMF" },
  { "name": "O‘zbekiston davlat sport akademiyasi", "abbr": "ODSA" },
  { "name": "Oʻzbekiston davlat xoreografiya akademiyasi", "abbr": "ODXA" },
  { "name": "Oʻzbekiston davlat xoreografiya akademiyasi Urganch filiali", "abbr": "ODXAUF" },
  { "name": "O‘zbekiston jurnalistika va ommaviy kommunikatsiyalar universiteti", "abbr": "OJOKU" },
  { "name": "O‘zbekiston Respublikasi Bank-moliya akademiyasi", "abbr": "ORBA" },
  { "name": "O‘zbekiston Respublikasi Davlat soliq qo‘mitasi huzuridagi Fiskal institut", "abbr": "ORDSQHFI" },
  { "name": "Oʻzbekiston Respublikasi Favqulodda vaziyatlar vazirligi Akademiyasi", "abbr": "ORFVVA" },
  { "name": "O‘zbekiston Respublikasi Huquqni muhofaza qilish akademiyasi", "abbr": "ORHMQA" },
  { "name": "O'zbekiston Respublikasi Prezidenti huzuridagi Davlat siyosati va boshqaruvi akademiyasi", "abbr": "ORPHDSBA" },
  { "name": "O‘zbekiston xalqaro islomshunoslik akademiyasi", "abbr": "OXIA" },
  { "name": "Shahrisabz davlat pedagogika instituti", "abbr": "SDPI" },
  { "name": "Sharof Rashidov nomidagi Samarqand davlat universiteti", "abbr": "SDU" },
  { "name": "Sharof Rashidov nomidagi Samarqand davlat universitetining Urgut filiali", "abbr": "SDUUF" },
  { "name": "Sharq University", "abbr": "SU" },
  { "name": "Chirchiq davlat pedagogika universiteti", "abbr": "CDPU" },
  { "name": "Chirchiq shahrida M.Auezov nomidagi Janubiy Qozog'oston universiteti", "abbr": "JQU" }
];
